@startuml
left to right direction
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 100
hide stereotype
skinparam rectangle {
    BackgroundColor #ffffff
    BorderColor #232f3e
    BorderThickness 2
    FontStyle bold
}
skinparam rectangle<<region>> {
    BackgroundColor transparent
    BorderColor #232f3e
    BorderThickness 2
}
skinparam rectangle<<vpc>> {
    BorderColor #16a34a
}
skinparam rectangle<<subnet_public>> {
    BorderColor #2563eb
}
skinparam rectangle<<subnet_private>> {
    BorderColor #64748b
}
skinparam component {
    BackgroundColor white
    BorderColor #f97316
    BorderThickness 1
}

rectangle "REGION" <<region>> as group_1774274891340 {
  rectangle "SUBNET PUBLIC" <<subnet_public>> as group_1774274906834 {
    component "<img:http://localhost:5173/icons/Architecture-Service-Icons_01302026/Arch_Compute/64/Arch_Amazon-EC2_64.png{scale=0.5}>\nAmazon EC2" as node_1774274932627
    component "<img:http://localhost:5173/icons/Architecture-Service-Icons_01302026/Arch_Databases/64/Arch_Amazon-RDS_64.png{scale=0.5}>\nAmazon RDS" as node_1774274934483
  }
  rectangle "VPC" <<vpc>> as group_1774274900621 {
    component "<img:http://localhost:5173/icons/Architecture-Service-Icons_01302026/Arch_Networking-Content-Delivery/64/Arch_Amazon-API-Gateway_64.png{scale=0.5}>\nAmazon API Gateway" as node_1774274952168
  }
  rectangle "SUBNET PRIVATE" <<subnet_private>> as group_1774274908052 {
    component "<img:http://localhost:5173/icons/Architecture-Service-Icons_01302026/Arch_Compute/64/Arch_Amazon-EC2_64.png{scale=0.5}>\nAmazon EC2" as node_1774274959855
  }
}
rectangle "REGION" <<region>> as group_1774274895930 {
  component "<img:http://localhost:5173/icons/Resource-Icons_01302026/Res_General-Icons/Res_48_Light/Res_Servers_48_Light.png{scale=0.5}>\nServers" as node_1774275052879
  component "<img:http://localhost:5173/icons/Resource-Icons_01302026/Res_General-Icons/Res_48_Light/Res_Servers_48_Light.png{scale=0.5}>\nServers" as node_1774275050075
}
rectangle "VPC" <<vpc>> as group_1774274898137 {
  component "<img:http://localhost:5173/icons/Resource-Icons_01302026/Res_General-Icons/Res_48_Light/Res_Folders_48_Light.png{scale=0.5}>\nFolders" as node_1774275041307
  component "<img:http://localhost:5173/icons/Resource-Icons_01302026/Res_General-Icons/Res_48_Light/Res_Folder_48_Light.png{scale=0.5}>\nFolder" as node_1774275043363
}

node_1774274952168 -down-> node_1774274959855
node_1774274934483 -down-> node_1774274952168
node_1774274932627 -down-> node_1774274934483
group_1774274891340 -down-> group_1774274895930
group_1774274891340 -down-> group_1774274898137
@enduml